config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  devise_for :users
  get 'notifications/read', to: 'notifications#read', as: :notifications
  resources :profiles do
    collection do
      get 'ownlist', 'follow', 'unfollow', 'sendrequest', 'unsendrequest', 'search', 'find'
    end
  end
  resources :posts
  resources :posts_api, only: [:show] do
    resources :post_likes_api, only: [:create, :destroy]
    resources :comments_api, only: [:index, :create, :destroy] do
      collection do
        get 'likesOrder'
      end
      resources :likes_api, only: [:create, :destroy]
    end
    collection do
        get 'free', 'info', 'question', 'intro','best'
    end
  end
  resources :profiles_api
  resources :requests, only: [:index]
  resources :requests_api do
    collection do
      get 'ownlist', 'accept', 'met', 'sendList', 'metList'
      post 'evaluation'
    end
  end
  # Message Part
  resources :messages do
    collection do
      get 'read'
    end
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  mount_uploader :userimage, UserimageUploader
  belongs_to :user
  validates :intro, length: { maximum: 200 }
  validate :userimage_size

  private

  def userimage_size
    return unless userimage.size > 1.megabytes
    errors.add(:userimage, '프로필 사진 용량은 1MB를 초과할 수 없습니다.')
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :show, :edit, :update]
  before_filter :make_profile, except: [:new, :create, :edit, :update]

  def index
    @message = current_user.sending_messages.build
  end

  def new
    if current_user.profile.nil?
      @profile = current_user.build_profile
    else
      redirect_to root_path
    end
  end

  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def ownlist
    @profiles = current_user.following
    @sign_in = true if user_signed_in?
    render json: @profiles, meta: {signIn: @sign_in}
  end

  def show
    @profile = Profile.find(params[:id])
  end

  def edit
    @profile = Profile.find(params[:id])
    redirect_to root_path unless @profile == current_user.profile
  end

  def update
    @profile = current_user.profile
    if @profile.update(profile_params)
      redirect_to profile_path(@profile)
    else
      render 'edit'
    end
  end

  def follow
    @profile = Profile.find(params[:profile_id])
    current_user.follow(@profile.user)
    render json: @profile
  end

  def unfollow
    @profile = Profile.find(params[:profile_id])
    current_user.unfollow(@profile.user)
    render json: @profile
  end

  def sendrequest
    @receiver = User.find(params[:receiver_id])
    @profile = @receiver.profile
    if current_user.request(@receiver)
      render json: @profile
    end
  end

  def unsendrequest
    @receiver = User.find(params[:receiver_id])
    @profile = @receiver.profile
    if current_user.unrequest(@receiver)
      render json: @profile
    end
  end

  def search
    if params.has_key?(:search)
      @profiles = Profile.where('username LIKE ?', "%#{params[:search]}%").limit(5) if params[:search].length > 0
    else
      @profiles = Profile.all
      @profiles = @profiles.where("nation LIKE ?", "#{params[:nation]}") if params[:nation]
      @profiles = @profiles.where("gender LIKE ?", "#{params[:gender]}") if params[:gender]
      @profiles = @profiles.where("age >= #{params[:minAge]}") if params[:minAge]
      @profiles = @profiles.where("age <= #{params[:maxAge]}") if params[:maxAge]
    end
    render json: @profiles
  end

  def find
  end

  private

  def make_profile
    if user_signed_in?
      if current_user.profile.nil?
        redirect_to new_profile_path
      end
    end
  end

  def profile_params
    params.require(:profile).permit(:username, :gender, :region, :nation, :interest, :intro, :userimage)
  end
end

app/views/profiles/edit.html.erb
<%= stylesheet_link_tag 'profiles/edit', media: 'all' %>
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="edit-box clearfix">
      <%= simple_form_for(@profile, url: profile_path(@profile), method: 'PATCH') do |f| %>
          <div class="row">
            <div class="box-title">
              <h2><%= t('profile.profileRevise')%></h2>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="left-box">
                <div class="img-wrapper">
                  <%= image_tag @profile.userimage.url.to_s, id: 'img_prev' %>
                </div>
                <%= f.input :userimage, label: "프로필 파일 선택", input_html: {onchange: "readURL(this)"} %>
                <div class="caption">
                  프로필 사진은 되도록 1:1 비율을 지켜주세요. 다른 비율인 경우 업로드시 1:1 비율로 변환됩니다.
                </div>
                <%= f.input :username, label: t('profile.nickname') %>
                <%= f.input :region, label: t('profile.region') %>
              </div>
            </div>
            <div class="col-md-6">
              <%= f.input :nation, label: t('profile.nation'), as: :select, collection: [:한국, :중국],
                          prompt: "국적을 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :gender, label: t('profile.gender'), as: :select, collection: [:남성, :여성],
                          prompt: "성별을 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :age, label: t('profile.age'), as: :select, collection: 1..100, prompt: "나이를 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :chinese_point, label: t('profile.chinesePoint'), as: :select, collection: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], prompt: "나이를 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :korean_point, label: t('profile.koreanPoint'), as: :select, collection: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], prompt: "나이를 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :interest, label: t('profile.interest') %>
              <%= f.input :intro, label: t('profile.intro') %>
            </div>
          </div>
          <%= f.button :submit, t('profile.reviseBtn'), class: "btn btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
</div>

<!--upload image input-->
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#img_prev')
                        .attr('src', e.target.result)
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

app/views/profiles/find.html.erb
<%= stylesheet_link_tag 'profiles/find', media: 'all' %>
<%= javascript_include_tag 'components/profile_find' %>
<%= react_component('ProfileFindBox', url: search_profiles_path) %>

app/views/profiles/index.html.erb
<%= stylesheet_link_tag 'profiles/index', media: 'all' %>
<div id="content"></div>
<nav id="page-nav">
  <%= link_to "", profiles_path(page: 2) %>
</nav>
<%= javascript_include_tag 'profiles_index' %>


<!-- Modal -->
<div class="modal fade" id="message" tabindex="-1" role="dialog" aria-labelledby="sendMessageModal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">쪽지 보내기(发送信息)</h4>
      </div>
      <div class="modal-body">
        <%= simple_form_for @message, url: messages_path, method: :post do |f| %>
            <%= f.error_notification %>
            <%= f.input :message, as: :text %>
            <%= f.hidden_field :receiver_id, value: '' %>
            <br/>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <%= f.button :submit, '전송(发送', class: 'btn btn-primary' %>

        <% end %>
        </div>
        </div>
  </div>
</div>
<!--쉐도우설정-->
<script type="text/javascript">
	$('.image-section-wrapper').hover(function () {
		var kids = $(this).find('.box-tooltip');
		kids.css('opacity', 1);
	}, function () {
		var kids = $(this).find('.box-tooltip');
		kids.css('opacity', 0);
	});
</script>
<!--모달 설정-->
<script type="text/javascript">
	$('#message').on('show.bs.modal', function (event) {
		var button = $(event.relatedTarget);
		var recipient = button.data('id');
		var modal = $(this);
		modal.find('#message_receiver_id').val(recipient);
	})
</script>

app/views/profiles/index2.html.erb
<%= react_component('ProfileIndexBox', url: profiles_path) %>

app/views/profiles/new.html.erb
<%= stylesheet_link_tag 'profiles/new', media: 'all' %>
<div class="container">
  <div class="col-md-8 col-md-offset-2">
    <div class="new-profile-box clearfix">
      <%= simple_form_for(@profile, url: profiles_path, method: 'POST') do |f| %>
          <div class="row">
            <div class="box-title">
              <h2><%= t('profile.profileSubmit')%></h2>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="left-box">
                <div class="img-wrapper">
                  <%= image_tag @profile.userimage.url.to_s, id: 'img_prev' %>
                </div>
                <%= f.input :userimage, label: "프로필 파일 선택", input_html: {onchange: "readURL(this)"} %>
                <div class="caption">
                  프로필 사진은 되도록 1:1 비율을 지켜주세요. 다른 비율인 경우 업로드시 1:1 비율로 변환됩니다.
                </div>
                <%= f.input :username, label: t('profile.nickname') %>
                <%= f.input :region, label: t('profile.region') %>
              </div>
            </div>
            <div class="col-md-6">
              <%= f.input :nation, label: t('profile.nation'), as: :select, collection: [:한국, :중국],
                          prompt: "국적을 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :gender, label: t('profile.gender'), as: :select, collection: [:남성, :여성],
                          prompt: "성별을 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :age, label: t('profile.age'), as: :select, collection: 1..100, prompt: "나이를 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :chinese_point, label: t('profile.chinesePoint'), as: :select, collection: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], prompt: "나이를 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :korean_point, label: t('profile.koreanPoint'), as: :select, collection: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100], prompt: "나이를 선택하세요.", html: {class: "form-control"} %>
              <%= f.input :interest, label: t('profile.interest') %>
              <%= f.input :intro, label: t('profile.intro') %>
            </div>
          </div>
          <%= f.button :submit, t('profile.submitBtn'), class: "btn btn-primary pull-right" %>
      <% end %>
    </div>
  </div>
</div>

<!--upload image input-->
<script>
    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#img_prev')
                        .attr('src', e.target.result)
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

app/views/profiles/show.html.erb
<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/moment.min.js"></script>
<% if cookies[:educator_locale] == 'zh-CN' %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/zh-cn.js"></script>
<% else %>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.6/locale/ko.js"></script>
<% end %>
<%= stylesheet_link_tag 'profiles/show', media: 'all' %>
<%= javascript_include_tag 'components/profile_show' %>
<%= react_component('ProfileBox', url: profiles_api_path(@profile)) %>