config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  devise_for :users
  get 'notifications/read', to: 'notifications#read', as: :notifications
  resources :profiles do
    collection do
      get 'ownlist', 'follow', 'unfollow', 'sendrequest', 'unsendrequest', 'search', 'find'
    end
  end
  resources :posts
  resources :posts_api, only: [:show] do
    resources :post_likes_api, only: [:create, :destroy]
    resources :comments_api, only: [:index, :create, :destroy] do
      collection do
        get 'likesOrder'
      end
      resources :likes_api, only: [:create, :destroy]
    end
    collection do
        get 'free', 'info', 'question', 'intro','best'
    end
  end
  resources :profiles_api
  resources :requests, only: [:index]
  resources :requests_api do
    collection do
      get 'ownlist', 'accept', 'met', 'sendList', 'metList'
      post 'evaluation'
    end
  end
  # Message Part
  resources :messages do
    collection do
      get 'read'
    end
  end
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container">
<!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button aria-expanded="false" class="navbar-toggle collapsed" data-target="#bs-example-navbar-collapse-1" data-toggle="collapse" type="button">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "一起친구", root_path, class: 'navbar-brand' %>
      <% if user_signed_in? %>
          <li class="dropdown visible-xs">
            <a class="dropdown-toggle alarm-dropdown navbar-brand pull-right" data-toggle="dropdown" href="#">
                <%= fa_icon "bell" %>
                <span class="notReadCounter"><%= current_user.count_unread_noti %></span>
            </a>
            <ul class="dropdown-menu mini-alarm" role="menu">
                <%= render 'layouts/notification' %>
            </ul>
          </li>
      <% end %>
    </div>

<!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to find_profiles_path do %>
          <%= t('menu.find_friend') %>
          <span class="sr-only">(current)</span>
          <% end %>
        </li>
        <li><%= link_to t('menu.board'), posts_path %></li>
      </ul>
      <form class="navbar-form navbar-left hidden-xs quick-search" role="search">
        <div class="form-group">
          <input class="form-control quick-search-field" name="searchField" placeholder="Search" type="text">
        </div>
        <ul class="dropdown-menu search-result"></ul>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="dropdown hidden-xs">
          <a class="dropdown-toggle alarm-dropdown" data-toggle="dropdown" href="#">
            <%= fa_icon "bell" %>
            <span class="notReadCounter"><%= current_user.count_unread_noti %></span>
          </a>
          <ul class="dropdown-menu noti-dropdown" role="menu">
              <%= render 'layouts/notification' %>
          </ul>
        </li>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <%= t('menu.languages.lang') %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li>
              <%= link_to t('menu.languages.zh-CN'), change_locale_path('zh-CN') %>
            </li>
            <li>
              <%= link_to t('menu.languages.ko'), change_locale_path('ko') %>
            </li>
          </ul>
        </li>
        <li class="dropdown">
          <a aria-expanded="false" aria-haspopup="true" class="dropdown-toggle" data-toggle="dropdown" href="#" role="button">
            <%= current_user.email %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "쪽지", messages_path %></li>
            <% unless current_user.profile.nil? || current_user.profile.username.nil? %>
            <li><%= link_to "프로필 수정", edit_profile_path(current_user.profile) %></li>
            <% end %>
            <li class="divider hidden-xs" role="separator"></li>
            <li><%= link_to "로그아웃", destroy_user_session_path, method: 'DELETE' %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "로그인", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
<!-- /.navbar-collapse -->
  </div>
<!-- /.container-fluid -->
</nav>

<script type="text/javascript">
  $(document).on("keyup", '[name=searchField]', function () {
    $.ajax({
      url: "/profiles/search",
      dataType: "json",
      data: {
        search: this.value
      },
      success: function (data) {
        console.log(data);
        $('.search-result li').remove();
        if (data.profiles.length == 0 || data == null) {
          $('.search-result').css('display', 'none');
        } else {
          $('.search-result').css('display', 'block');
        }
        data.profiles.map(function (d) {
          $('.search-result').append('<a href=' + d.url +
              '><li><img src=' + d.nano_user_image + ' width="50" height="50" />' + d.username + '</li></a>');
        });
      },
      error: function () {
        console.log("error!!");
      }
    });
  });
  $(document).on("click", '.alarm-dropdown', function () {
    $('.notReadCounter').hide();
    $.ajax({
      url: "/notifications/read",
      dataType: 'json',
      success: function (res) {
        $('.notReadCounter').hide();
      },
      error: function () {
        console.log("Alarm Update Error!!")
      }
    });
  });
</script>

app/views/layouts/_notification.html.erb
<% if user_signed_in? %>
    <% if current_user.notifications.length === 0 %>
        <li class="clearfix"><a href="#">알림이 없습니다.</a></li>
    <% else %>
        <% current_user.notifications.order("created_at DESC").each do |noti| %>
            <% case noti.noti_type %>
                <% when "comment" %>
                    <li>
                      <%= link_to post_path(noti.post_id) do %>
                          <%= noti.post.title.truncate(10, ommision: '...') %>에 <strong><%= noti.sender %></strong> 님이 댓글을 남겼습니다.
                          <p class="created-at hidden-xs"><%= noti.created_at.strftime "%y-%m-%d %H:%M" %></p>
                      <% end %>
                    </li>
                <% when "post_like" %>
                    <li>
                      <%= link_to post_path(noti.post_id) do %>
                          <%= noti.post.title.truncate(10, ommision: '...') %>을 <strong><%= noti.sender %></strong> 님이 좋아합니다.
                          <p class="created-at hidden-xs"><%= noti.created_at.strftime "%y-%m-%d %H:%M" %></p>
                      <% end %>
                    </li>
                <% when "comment_like" %>
                    <li>
                      <%= link_to post_path(noti.post_id) do %>
                          <%= noti.comment.comment.truncate(10, ommision: '...') %>을 <strong><%= noti.sender %></strong> 님이 좋아합니다.
                          <p class="created-at hidden-xs"><%= noti.created_at.strftime "%y-%m-%d %H:%M" %></p>
                      <% end %>
                    </li>
                <% when "request" %>
                    <li>
                      <%= link_to profile_path(noti.sender_profile_id) do %>
                          <strong><%= noti.sender %></strong> 님이 회원님께 만남 신청을 했습니다.
                          <p class="created-at hidden-xs"><%= noti.created_at.strftime "%y-%m-%d %H:%M" %></p>
                      <% end %>
                    </li>
                <% when "follow" %>
                    <li>
                      <%= link_to profile_path(noti.sender_profile_id) do %>
                          <strong><%= noti.sender %></strong> 님이 회원님을 팔로우합니다.
                          <p class="created-at hidden-xs"><%= noti.created_at.strftime "%y-%m-%d %H:%M" %></p>
                      <% end %>
                    </li>
            <% end %>
        <% end %>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>一起친구! 1779!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
  <%= render 'layouts/navbar' %>
  <%= yield %>
  <% console if Rails.env.development? %>
  <%-# debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>一起친구! 1779!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.blue-amber.min.css" />
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <script src="https://storage.googleapis.com/code.getmdl.io/1.0.0/material.min.js"></script>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
      <div class="mdl-layout-icon"></div>
      <div class="mdl-layout__header-row">
        <span class="mdl-layout-title"><%= link_to '一起친구', root_path %></span>
        <div class="mdl-layout-spacer"></div>
        <nav class="mdl-navigation mdl-layout--large-screen-only">
          <% if user_signed_in? %>
            <div class="mdl-textfield mdl-js-textfield mdl-textfield--expandable
              mdl-textfield--floating-label mdl-textfield--align-right">
              <label class="mdl-button mdl-js-button mdl-button--icon"
               for="fixed-header-drawer-exp">
               <i class="material-icons">search</i>
              </label>
              <div class="mdl-textfield__expandable-holder">
                <input class="mdl-textfield__input" type="text" name="searchField"
                  id="fixed-header-drawer-exp" />
                <ul class="dropdown-menu search-result">
                </ul>
              </div>
            </div>
            <%= link_to "회원정보수정", edit_profile_path(current_user.profile), class: "mdl-navigation__link" %>
            <%= link_to "쪽지함", messages_path, class: "mdl-navigation__link" %>
            <%= link_to "Log out", destroy_user_session_path, method: 'DELETE', class: "mdl-navigation__link" %>
          <% else %>
            <%= link_to t('menu.signup'), new_user_registration_path, class: "mdl-navigation__link" %>
            <%= link_to t('menu.signin'), new_user_session_path, class: "mdl-navigation__link" %>
          <% end %>
        </nav>
      </div>
    </header>
    <div class="mdl-layout__drawer">
      <span class="mdl-layout-title">一起친구</span>
      <nav class="mdl-navigation">
        <% if user_signed_in? %>
          <%= link_to "회원정보수정", edit_profile_path(current_user.profile), class: "mdl-navigation__link" %>
          <%= link_to "쪽지함", messages_path, class: "mdl-navigation__link" %>
          <%= link_to "Log out", destroy_user_session_path, method: 'DELETE', class: "mdl-navigation__link" %>
        <% else %>
          <%= link_to t('menu.signup'), new_user_registration_path, class: "mdl-navigation__link" %>
          <%= link_to t('menu.signin'), new_user_session_path, class: "mdl-navigation__link" %>
        <% end %>
      </nav>
    </div>
    <main class="mdl-layout__content">
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </main>
  </div>
  <script type="text/javascript">
    $(document).on("keyup", '[name=searchField]', function() {
      $.ajax({
        url: "/profiles/search",
        dataType: "json",
        data: {search: this.value},
        success: function(data) {
          console.log(data);
          $('.search-result li').remove();
          if(data.profiles.length == 0 || data == null) {
            $('.search-result').css('display', 'none');
          }
          else {
            $('.search-result').css('display', 'block');
          }
          data.profiles.map(function(d) {
            $('.search-result').append('<a href='+ d.url +'><li><img src='+ d.nano_user_image + ' width="50" height="50" />' + d.username +'</li></a>');
          });
        },
        error: function() {
          console.log("error!!");
        }
      });
    });
  </script>
</body>
</html>

app/views/layouts/no_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>一起친구! 1779!</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body>
  <%= yield %>
  <%-# debug(params) if Rails.env.development? %>
</body>
</html>